export const STATUS_LIST = [
  "Waiting for Input",
  "Released",
  "Analysis",
  "In Review",
  "PR Raised",
  "Analysis/Comment added",
  "Blocked",
  "Blocked/Comment added",
  "Blocked/Waiting for Input",
  "Waiting for Input",
  "Review suggestions applied",
];

export const PAGE_CONFIGS = [
  {
    id: "board-view",
    urlPattern: /\/boards\//,
    selectors: {
      row: "[data-testid=\"platform-board-kit.ui.card.card\"]",
      ticketId: "[data-testid=\"platform-card.common.ui.key.key\"] a",
      title: "[data-testid=\"issue-field-single-line-text-readview-card.ui.single-line-text.container.box\"]",
      status: "[data-testid=\"platform-card.common.ui.custom-fields.card-custom-field.text-card-custom-field-content.field\"]",
      buttonContainer: "[data-testid=\"platform-card.ui.card.card-content.footer\"] > div > div:first-child",
    },
    buttons: ["listLinkButton"],
    buttonClass: "jira-list-copy-link-btn",
    settingKey: "enableListView",
  },
  {
    id: "release-view",
    urlPattern: /\/versions\/.*\/tab\//,
    selectors: {
      row: "[data-testid=\"software-releases-version-detail-issue-list.ui.issues.issue-card\"]",
      ticketId: "img + span",
      title: "[role=\"presentation\"] div",
      status: "[data-testid=\"common-components-status-lozenge.status-lozenge--text\"]",
      buttonContainer: "[role=\"presentation\"]",
    },
    buttons: ["listLinkButton"],
    buttonClass: "jira-list-copy-link-btn",
    settingKey: "enableListView",
  },
  {
    id: "ticket-detail",
    urlPattern: /\/browse\/|\/issues\/|\/jira\/software\/|\/projects\//,
    selectors: {
      ticketId: "[data-testid=\"issue.views.issue-base.foundation.breadcrumbs.current-issue.item\"]",
      status: "[data-testid=\"issue-field-status.ui.status-view.status-button.status-button\"]",
      title: "[data-testid='issue.views.issue-base.foundation.summary.heading']",
      container: "[data-testid='issue.views.issue-base.foundation.status.status-field-wrapper']",
      insertAfter: "[data-testid='issue.views.issue-base.foundation.breadcrumbs.breadcrumb-current-issue-container']",
    },
    buttons: ["copyTicketInfo", "statusDropdown", "gitButton", "linkButton"],
    groupId: "jira-ticket-copier-group",
  },
  {
    id: "list-view",
    urlPattern: /\/jira\/software\/|\/issues\/|\/projects\//,
    excludePattern: /\/boards\/|\/versions\/.*\/tab\//,
    selectors: {
      row: "[role=\"row\"], .BaseTable__row",
      ticketId: "[data-testid=\"business-list.ui.list-view.key-cell.issue-key\"]",
      title: "[data-testid=\"business-list.ui.list-view.summary-cell\"]",
      status: "[data-testid=\"business-list.ui.list-view.status-cell.cell-container\"]",
      buttonContainer: "[data-testid=\"business-list.ui.list-view.text-cell.text-cell-wrapper\"]",
    },
    buttons: ["listLinkButton"],
    buttonClass: "jira-list-copy-link-btn",
    settingKey: "enableListView",
  },
];
