name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23.x'
      - run: npm install
      - run: npm run lint
      - run: npm test
      - run: npm run build
      - name: Package Extension
        run: npm run package
      - name: Upload ZIP artifact
        uses: actions/upload-artifact@v4
        with:
          name: jira-ticket-copier-zip
          path: jira-ticket-copier.zip
